2025-10-18 11:40:36,108 : INFO : root : Loading config.
2025-10-18 11:40:36,111 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-18 11:40:36,113 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\fdca14d0c9d658ab8200d57120800af5.mpf_cache
2025-10-18 11:40:36,223 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 11:40:36,223 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-10-18 11:40:36,225 : INFO : ConfigProcessor : Loading config: C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-10-18 11:40:36,225 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\nightpin\modes\attract\config\attract.yaml.
2025-10-18 11:40:36,227 : INFO : ConfigProcessor : Loading config: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 11:40:36,229 : INFO : ConfigProcessor : Config file cache created: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 11:40:36,229 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\202a5840610e95051f9f473dfa660cc0.mpf_cache
2025-10-18 11:40:36,230 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 11:40:36,232 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\2cd13a2d3f375e00ab01d6d09a85d8e7.mpf_cache
2025-10-18 11:40:36,234 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\antho\nightpin\shows\.\attract_lights.yaml
2025-10-18 11:40:36,234 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\nightpin\shows\.\attract_lights.yaml.
2025-10-18 11:40:36,253 : INFO : ConfigProcessor : Loading config: C:\Users\antho\nightpin\shows\.\attract_lights.yaml
2025-10-18 11:40:36,254 : INFO : ConfigProcessor : Config file cache created: C:\Users\antho\AppData\Local\Temp\dab29d17bbe6500d014c71b0a57bd9b0.mpf_cache
2025-10-18 11:40:36,254 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev11
2025-10-18 11:40:36,255 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-18-11-40-36-mpf-LAPTOP-MPGP6R69.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-11-40-36-mpf-LAPTOP-MPGP6R69.log'}
2025-10-18 11:40:36,255 : INFO : Machine : MPF path: C:\Users\antho\mpf\Lib\site-packages\mpf
2025-10-18 11:40:36,255 : INFO : Machine : Machine path: C:\Users\antho\nightpin
2025-10-18 11:40:36,255 : INFO : Machine : Platform: win32
2025-10-18 11:40:36,255 : INFO : Machine : Python executable location: C:\Users\antho\mpf\Scripts\python.exe
2025-10-18 11:40:36,255 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-10-18 11:40:36,257 : INFO : Machine : Initializing MPF...
2025-10-18 11:40:36,353 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,380 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-18 11:40:36,380 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,380 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,380 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-11-40-36-mpf-LAPTOP-MPGP6R69.log', 'prev_value': None, 'change': True}
2025-10-18 11:40:36,536 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-18 11:40:36,557 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-18 11:40:36,560 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2025-10-18 11:40:36,560 : INFO : ball_device.bd_trough : State: idle
2025-10-18 11:40:36,567 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-18 11:40:36,570 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe... 0 duration')>)
handle: <Handle EventManager._queue_task_done(<Task finishe... 0 duration')>)>
Traceback (most recent call last):
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 160, in load
    self._show_validation_error("Step {} has 0 duration".format(step_num), 7)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_lights" >> Step 1 has 0 duration Context: attract_lights Error Code: CFE-show-7 (https://missionpinball.org/logs)
2025-10-18 11:40:36,603 : INFO : Machine : Starting the main run loop with active modes: []
2025-10-18 11:40:36,603 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-10-18 11:40:36,604 : INFO : Machine : Shutting down...
2025-10-18 11:40:36,604 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-18 11:40:37,613 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\machine.py", line 810, in _run_loop
    raise self._exception['exception']
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 160, in load
    self._show_validation_error("Step {} has 0 duration".format(step_num), 7)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_lights" >> Step 1 has 0 duration Context: attract_lights Error Code: CFE-show-7 (https://missionpinball.org/logs)
2025-10-18 11:40:37,615 : INFO : root : MPF run loop ended.
